### ISSUE TITLE
z-index compatible

### ISSUE THREAD

**Issue by adrianobr** [tleish/redmine_jstoolbar_ext#1]
Please add: z-index: 1;
Compatibility whith All themes
.jstb_coderay_submenu { width: 240px; z-index:1; }

**Comment by tleish** [comment]
Fixed in https://github.com/tleish/redmine_jstoolbar_ext_coderay/commit/47de569e83ea8df24dd5e1b752ffa1b24e655ecc 

Note: the fix was part of tleish/redmine_jstoolbar_ext_**coderay**, not this project.  You will want to pull the latest update from there.
